// <auto-generated />
namespace WebApplicationAssistiveDeviceRentAPIv01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class UpdateUserTable_AddRegexNUniqueLimit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateUserTable_AddRegexNUniqueLimit));
        
        string IMigrationMetadata.Id
        {
            get { return "202412241755484_UpdateUserTable_AddRegexNUniqueLimit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
